name: gha release created

on:
  release:
    types:
      - released
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: do something
      run: |
        echo 'do something'
